#######
# This file is specified as input to the ddprofiler, which uses it to extract a list of
# sources that are necessary to process and profile.
#
# This file consists of an attribute 'sources' which is a list of
# data sources, that describe the different sources that need to be processed.
# Each source has three mandatory attributes, 'name', which will be
# used to refer to the source and should be descriptive. 'type', which indicates what
# type of source we are dealing with, one of [csv, postgres, mysql, oracle10g, oracle11g].
# Finally, a 'config' object, which will contain source specific properties.
#
# Each type of source has a different set of properties that are necessary to configure it.
# These are all part of the 'config' object, that each source contains.
# For example, a folder in a filesystem will require a path, while a database server will
# require credentials to access it. We document the properties required by each source below.
#######

api_version: 0

# In sources we include as many data sources as desired
sources:

# Include a source for each data source to configure

  # name to identify each source, e.g., migration_database, production, lake, etc.
- name: "nextiaJD_testbedXS_csv_repository"
  # indicate the type of source, one of [csv, postgres, mysql, oracle10g, oracle11g]  
  type: csv
  config:
    # path indicates where the CSV files live
    path: "/data/nextiaJD_datasets/aurum_only/testbedXS/semicolon/"
    # separator used in the CSV files
    separator: ";"
